### ISSUE TITLE
Workable Code?

### ISSUE THREAD

**Issue by urbanatwork** [rottaca/VPlotter2.0#1]
I am working with students and was looking for a python based v plotter. How workable is this code? Did you get it to work?

Thanks for your contribution.

**Comment by rottaca** [comment]
Yes, the plotter was fully working and it includes a python based simulation framework.
Unfortunately, I didn't have enough time to write a documentation and a tutorial (e.g. how the calibration works,...) do to a stay abroad.

It is fully functional and I remember drawing lots of pictures with it. I planned to implement a web interface but at the moment only a command line interface is available (plottermain.py). It can execute interactive GCode commands by typing them in the commandline and it runs GCode files (produced by one of the available generators. I used a customized gcode language and other gcode will most likely not work). The gcode is very simple, just have a look at the beginning of the file plotter/gcode_generators.py.

To convert images into gcode commands, use the gcodeGenerator.py script. A few different techniques are implemented but they are very basic. You should be able to implement your owe gcode generator if you want :).

In order to use the hardware plotter, you have to modify plotter/config.py (configuration of your stepper motors, distance between these motors and so on...). In order to draw something, you have to specify the distance between the motors and the print head as command line parameters, because the software needs to know the current position of the print head, before it can start moving. Here, the usability can be drastically improved! 

If you decide to use this framework, I would appreciate a Pull Request! :)

**Comment by urbanatwork** [comment]
Thanks again for posting your work. FYI: We weren't looking to make it web enabled. We just were looking to make it work with a pi-plate to draw some picture for the end of the school year.  We only have a week left and seem to be stuck.  We thought we had everything setup but we seem to have issues with the scipy libraries. Thanks.

**Comment by urbanatwork** [comment]
New raspian build and we still can't get past the dependencies. Mostly scipy. 
We have been trying to do them individually... 

PS:  there is a typo in: 
> ~/vplotterenv/bin/pip3 install **_wheeel_** numpy scipy imageio matplotlib RPi.GPIO rpimotorlib

**Comment by rottaca** [comment]
What pi-plate are you talking about ? The software was tested with pololu DRV8825 stepper drivers, directly connected to the PI's GPIO pins. Unfortunately, I don't have a raspberry pi lying around to help you with the hardware setup.

You're, right **wheeel** should be **wheel**.

If you're still having issues with installing scipy, try the following command:
`sudo apt-get install python3-scipy`

Test if everything works as expected by running: 
` python plottermain.py --backend sw --calib 300 600 --runfile simplenox.gcode`

This should draw a rectangular box inside the drawing area (if you have the simulation environment setup). You can also use this to test the hardware by switching the backend to "**hw**". The file **monalisa.gcode** contains a more complex example to render.

PS: Sorry for editing the comment that often :)

**Comment by urbanatwork** [comment]
Thanks for the attention. I went all the way back and installed a fresh copy of raspbian on the SD card. The original build was a NOOBS build and was taking up most of the 8Gb card. I thought maybe the library imports, and builds, were maxing out the cache. There is now plenty of space but still running into issues from scipy.  

I followed all of your commands, including the environment setup. It might be worth noting for others that imageio won't import without pillow. Pillow won't import without another dependency.

Needed for pillow install:
 `sudo apt-get install libjpeg-dev`


**Results so far:** 

```
(vplotterenv) pi@piPlotter2:~/VPlotter2.0 $ sudo apt-get install python3-scipy
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-scipy is already the newest version (0.18.1-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
(vplotterenv) pi@piPlotter2:~/VPlotter2.0 $ python3 plottermain.py --backend sw --calib 300 600 --runfile monalisa.gcode
Traceback (most recent call last):
  File "plottermain.py", line 15, in <module>
    from plotter import plotter
  File "/home/pi/VPlotter2.0/plotter/plotter.py", line 9, in <module>
    from . import gcode_generators
  File "/home/pi/VPlotter2.0/plotter/gcode_generators.py", line 1, in <module>
    import scipy as sp
ImportError: No module named 'scipy'
(vplotterenv) pi@piPlotter2:~/VPlotter2.0 $ 

```

After trying to install part of the original command I notice it is a different version of scipy.

**I imagine this is all my issue and doesn't reflect the quality of your software.**  I am not sure I have the time to look through scipy's build issues. Maybe I'll look to see if I can hack scipy out of the original code but I only have this week to complete the project (school is almost over!)

Thanks again.

FYI:::::
ERROR:
```
(vplotterenv) pi@piPlotter2:~/VPlotter2.0 $ ~/vplotterenv/bin/pip3 install scipy
Collecting scipy
  Using cached https://files.pythonhosted.org/packages/cb/97/361c8c6ceb3eb765371a702ea873ff2fe112fa40073e7d2b8199db8eb56e/scipy-1.3.0.tar.gz
Building wheels for collected packages: scipy
  Running setup.py bdist_wheel for scipy ... error
  Complete output from command /home/pi/vplotterenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-uydyz_hq/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmprcjhvcftpip-wheel- --python-tag cp35:
  /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
    warnings.warn(msg)
  Running from scipy source directory.
  lapack_opt_info:
  lapack_mkl_info:
  customize UnixCCompiler
    libraries mkl_rt not found in ['/home/pi/vplotterenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
    NOT AVAILABLE
  
  openblas_lapack_info:
  customize UnixCCompiler
  customize UnixCCompiler
    libraries openblas not found in ['/home/pi/vplotterenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
    NOT AVAILABLE
  
  openblas_clapack_info:
  customize UnixCCompiler
  customize UnixCCompiler
    libraries openblas,lapack not found in ['/home/pi/vplotterenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
    NOT AVAILABLE
  
  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
  customize UnixCCompiler
    libraries lapack_atlas not found in /home/pi/vplotterenv/lib
  customize UnixCCompiler
    libraries tatlas,tatlas not found in /home/pi/vplotterenv/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries tatlas,tatlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib
  customize UnixCCompiler
    libraries tatlas,tatlas not found in /usr/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
  customize UnixCCompiler
    libraries tatlas,tatlas not found in /usr/lib/arm-linux-gnueabihf
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE
  
  atlas_3_10_info:
  customize UnixCCompiler
    libraries lapack_atlas not found in /home/pi/vplotterenv/lib
  customize UnixCCompiler
    libraries satlas,satlas not found in /home/pi/vplotterenv/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries satlas,satlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib
  customize UnixCCompiler
    libraries satlas,satlas not found in /usr/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
  customize UnixCCompiler
    libraries satlas,satlas not found in /usr/lib/arm-linux-gnueabihf
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE
  
  atlas_threads_info:
  Setting PTATLAS=ATLAS
  customize UnixCCompiler
    libraries lapack_atlas not found in /home/pi/vplotterenv/lib
  customize UnixCCompiler
    libraries ptf77blas,ptcblas,atlas not found in /home/pi/vplotterenv/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib
  customize UnixCCompiler
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
  customize UnixCCompiler
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib/arm-linux-gnueabihf
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE
  
  atlas_info:
  customize UnixCCompiler
    libraries lapack_atlas not found in /home/pi/vplotterenv/lib
  customize UnixCCompiler
    libraries f77blas,cblas,atlas not found in /home/pi/vplotterenv/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries f77blas,cblas,atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib
  customize UnixCCompiler
    libraries f77blas,cblas,atlas not found in /usr/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
  customize UnixCCompiler
    libraries f77blas,cblas,atlas not found in /usr/lib/arm-linux-gnueabihf
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE
  
  accelerate_info:
    NOT AVAILABLE
  
  /home/pi/vplotterenv/lib/python3.5/site-packages/numpy/distutils/system_info.py:639: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  lapack_info:
  customize UnixCCompiler
    libraries lapack not found in ['/home/pi/vplotterenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
    NOT AVAILABLE
  
  /home/pi/vplotterenv/lib/python3.5/site-packages/numpy/distutils/system_info.py:639: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE
  
  /home/pi/vplotterenv/lib/python3.5/site-packages/numpy/distutils/system_info.py:639: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-uydyz_hq/scipy/setup.py", line 505, in <module>
      setup_package()
    File "/tmp/pip-build-uydyz_hq/scipy/setup.py", line 501, in setup_package
      setup(**metadata)
    File "/home/pi/vplotterenv/lib/python3.5/site-packages/numpy/distutils/core.py", line 137, in setup
      config = configuration()
    File "/tmp/pip-build-uydyz_hq/scipy/setup.py", line 403, in configuration
      raise NotFoundError(msg)
  numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
  
  ----------------------------------------
  Failed building wheel for scipy
  Running setup.py clean for scipy
  Complete output from command /home/pi/vplotterenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-uydyz_hq/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  
  `setup.py clean` is not supported, use one of the following instead:
  
    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)
  
  Add `--force` to your command to use it anyway if you must (unsupported).
  
  
  ----------------------------------------
  Failed cleaning build dir for scipy
Failed to build scipy
Installing collected packages: scipy
  Running setup.py install for scipy ... error
    Complete output from command /home/pi/vplotterenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-uydyz_hq/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ga_b8yuu-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/vplotterenv/include/site/python3.5/scipy:
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)
    
    
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    Running from scipy source directory.
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/home/pi/vplotterenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    openblas_lapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/home/pi/vplotterenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    openblas_clapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas,lapack not found in ['/home/pi/vplotterenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/pi/vplotterenv/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /home/pi/vplotterenv/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/pi/vplotterenv/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /home/pi/vplotterenv/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/pi/vplotterenv/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /home/pi/vplotterenv/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/pi/vplotterenv/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /home/pi/vplotterenv/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    accelerate_info:
      NOT AVAILABLE
    
    /home/pi/vplotterenv/lib/python3.5/site-packages/numpy/distutils/system_info.py:639: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
    customize UnixCCompiler
      libraries lapack not found in ['/home/pi/vplotterenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    /home/pi/vplotterenv/lib/python3.5/site-packages/numpy/distutils/system_info.py:639: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE
    
    /home/pi/vplotterenv/lib/python3.5/site-packages/numpy/distutils/system_info.py:639: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-uydyz_hq/scipy/setup.py", line 505, in <module>
        setup_package()
      File "/tmp/pip-build-uydyz_hq/scipy/setup.py", line 501, in setup_package
        setup(**metadata)
      File "/home/pi/vplotterenv/lib/python3.5/site-packages/numpy/distutils/core.py", line 137, in setup
        config = configuration()
      File "/tmp/pip-build-uydyz_hq/scipy/setup.py", line 403, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
    
    ----------------------------------------
Command "/home/pi/vplotterenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-uydyz_hq/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ga_b8yuu-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/vplotterenv/include/site/python3.5/scipy" failed with error code 1 in /tmp/pip-build-uydyz_hq/scipy/
(vplotterenv) pi@piPlotter2:~/VPlotter2.0 $ 


```

**Comment by rottaca** [comment]
The import error you get is very weird. It should be possible to install the package by using pip or apt-get. Building from source is likely to be way more complicated.

I noticed that you get the error in plotter/gcode_generator.py. It might be possible that the import is currently not used at all. Try to comment out the import of scipy and see if that helps.
Sorry for the inconvenience!
